name: mern-app

services:
  client:
    build: ./client
    # Giving the container a name.
    container_name: client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
  server:
    # Telling docker-compose to build the client image using the Dockerfile in the server directory.
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: server
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - ./app/node_modules
    ports:
      - "5000:5000"
