version: 4.17.0
services:
  client:
    build: ./client
    # Giving the container a name.
    container_name: client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
  server:
    # Telling docker-compose to build the client image using the Dockerfile in the server directory.
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - ./app/node_modules
