name: Deploy Node App

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker logoin -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t johnathew/sleepie_mern .
      - name: Publish Image to Docker Hub
        run: docker push johnathew/sleepie_mern

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull johnathew/sleepie_mern
      - name: Run the Docker container
        run: docker run -d -p 5000:5000 --name sleepie_mern -e MONGO_CONNECTION_STRING=`${{secrets.MONGO_CONNECTION_STRING}}` johnathew/sleepie_mern
