name: Deploy MERN App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest
    # Checkout the code from the Github repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Client Docker Image
        working-directory: ./client
        run: |
          docker build -t johnathew/sleepie_mern:client-${{github.run_number}} .

      - name: Build Server Docker Image
        working-directory: ./server
        run: docker build -t johnathew/sleepie_mern:server-${{github.run_number}} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Client Image to Docker Hub
        run: docker push johnathew/sleepie_mern:client-${{github.run_number}}

      - name: Publish Server Image to Docker Hub
        run: docker push johnathew/sleepie_mern:server-${{github.run_number}}

  deploy-client:
    needs: build-client
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Pull Client Image from Docker Hub
        run: docker pull johnathew/sleepie_mern/client:latest

      - name: Delete Old Client Container
        run: docker rm -f sleepie_mern_client
        continue-on-error: true
      - name: Run Client Docker Container
        run: docker run -d -p 5173:5173 --name sleepie_mern_client johnathew/sleepie_mern/client:latest

  deploy-server:
    needs: deploy-client
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Pull Server Image from Docker Hub
        run: docker pull johnathew/sleepie_mern/server:latest

      - name: Delete Old Server Container
        run: docker rm -f sleepie_mern_server
        continue-on-error: true
      - name: Run Server Docker Container
        run: docker run -d -p 3000:3000 --name sleepie_mern_server -e MONGO_CONNECTION_STRING=${{secrets.MONGO_CONNECTION_STRING}} johnathew/sleepie_mern/server:latest
