name: Deploy MERN App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build Client Docker Image
        run: docker build -t johnathew/sleepie_mern/client ./client
      - name: Publish Client Image to Docker Hub
        run: docker push johnathew/sleepie_mern/client:latest

  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build Server Docker Image
        run: docker build -t johnathew/sleepie_mern/server ./server
      - name: Publish Server Image to Docker Hub
        run: docker push johnathew/sleepie_mern/server:latest

  deploy-client:
    needs: build-client
    runs-on: self-hosted
    steps:
      - name: Pull Client Image from Docker Hub
        run: docker pull johnathew/sleepie_mern/client:latest
      - name: Delete Old Client Container
        run: docker rm -f sleepie_mern_client
        continue-on-error: true
      - name: Run Client Docker Container
        run: docker run -d -p 5173:5173 --name sleepie_mern_client johnathew/sleepie_mern/client:latest

  deploy-server:
    needs: build-server
    runs-on: self-hosted
    steps:
      - name: Pull Server Image from Docker Hub
        run: docker pull johnathew/sleepie_mern/server:latest
      - name: Delete Old Server Container
        run: docker rm -f sleepie_mern_server
        continue-on-error: true
      - name: Run Server Docker Container
        run: docker run -d -p 3000:3000 --name sleepie_mern_server -e MONGO_CONNECTION_STRING=${{secrets.MONGO_CONNECTION_STRING}} johnathew/sleepie_mern/server:latest
